### ISSUE TITLE
Enable Test Coverage Reporting

### ISSUE THREAD

**Issue by mecampbellsoup** [zipmark/applications-api#3]
* [x] Add repo to Code Climate
* [x] Add CODECLIMATE_REPO_TOKEN as CI env variable
* [x] turn on reporting in the repo

**Comment by jakehow** [comment]
added to CC and added env var in circle

**Comment by mecampbellsoup** [comment]
@jakehow I can't do much aside from reading in CodeClimate, so if I need to toggle something there to turn on reporting I don't think I'm able to currently...

**Comment by jakehow** [comment]
@mecampbellsoup you just need to follow the instructions and push the changes to the repo, everything else is set up for you... see last checkbox above :)

**Comment by mecampbellsoup** [comment]
Done: https://github.com/zipmark/applications-api/blob/05f650473788581b877ced6154d96bd05063a015/spec/spec_helper.rb#L18-L19

**Comment by mecampbellsoup** [comment]
@jakehow https://codeclimate.com/repos/5761b82091d547007d0052ff/builds/2
